"""Regenerate the self-contained notebook whenever modules change."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
cells=[]
def md(s): cells.append({'cell_type':'markdown','metadata':{},'source':s.splitlines(True)})
def code(s): cells.append({'cell_type':'code','execution_count':None,'metadata':{},'outputs':[],'source':s.splitlines(True)})
md('# Metis · Hidden Market Regimes\n\nCan market states discovered without event labels help describe risk? This notebook runs a complete chronological experiment. **Default data is synthetic: do not interpret its returns as market evidence.**')
md('## 1. Setup and reproducibility\nKaggle normally provides NumPy, pandas, SciPy, scikit-learn, matplotlib and PyYAML. For downloads, install yfinance if needed with internet enabled. A CSV works offline. The source is embedded below, so no repository clone is required.')
payload={str(p.relative_to(root)):p.read_text() for p in sorted((root/'src').glob('*.py'))}
code('from pathlib import Path\nimport json, sys\nPROJECT = Path.cwd() / "metis_notebook_project"\nPROJECT.mkdir(exist_ok=True)\nSOURCES = '+repr(payload)+'\nfor name, text in SOURCES.items():\n    path = PROJECT / name\n    path.parent.mkdir(parents=True, exist_ok=True)\n    path.write_text(text)\nsys.path.insert(0, str(PROJECT))\n')
md('## 2. Data and experiment settings\nFor actual market research set `DEMO=False` and `CSV_PATH` to an attached Kaggle dataset with date, equity and bonds columns (optional gold, oil, dollar, vix). Adjust split dates before viewing test results. Price columns must be adjusted and complete. No future filling is performed.')
code('DEMO = True\nCSV_PATH = "/kaggle/input/your-dataset/market.csv"\nCONFIG = '+repr(__import__('yaml').safe_load((root/'config.yaml').read_text()))+'\nfrom src.data_loader import synthetic, load_csv\nprices = synthetic() if DEMO else load_csv(CSV_PATH)\nprint("SYNTHETIC SOFTWARE DEMO" if DEMO else "HISTORICAL DATA")\nprint(prices.shape, prices.index.min(), prices.index.max())\ndisplay(prices.head())')
md('## 3. Feature engineering\nAll windows end on the observation date. Returns already capture momentum. Scaling and PCA are learned only from training. Inspect distributions and correlations before drawing economic conclusions; the fitting pipeline itself does not use historical event names.')
code('from src.features import make_features\nfeatures = make_features(prices, CONFIG["windows"])\ndisplay(features.describe().T)')
md('## 4. Model fitting, validation and backtest\nK-Means and GMM provide baselines; the HMM models persistent hidden states. State count is selected on validation log likelihood within the HMM family. It is not chosen on test returns. The fixed training fit is carried forward through validation and test. Online filtering never uses future observations.\n\nThe full run below also performs window/training-length validation sensitivity and transaction-cost/allocation sensitivity. A signal at close t is executed at close t+1 and earns returns thereafter. This cell may take several minutes.')
code('from src.pipeline import run\nOUT = PROJECT / "outputs"\nmetrics = run(prices, CONFIG, OUT, DEMO)\ndisplay(metrics)')
md('## 5. Can unsupervised ML find structure?\nSilhouette is descriptive. K-Means score is negative squared distance, whereas GMM/HMM scores are log likelihood: do not compare these across families.')
code('import pandas as pd\ndisplay(pd.read_csv(OUT / "results/model_comparison.csv"))')
md('## 6. What did the model discover?\nState numbers are arbitrary. Interpret these training-only profiles before naming any state. Volatility rank determines allocation weights; recovery/crisis labels are not imposed.')
code('display(pd.read_csv(OUT / "results/training_state_profiles.csv"))\nfrom IPython.display import Image, display\nfor n in ["01_market_regimes", "02_timeline", "03_profiles", "06_pca", "13_feature_correlation", "14_return_distribution", "15_realized_volatility", "16_correlations"]:\n    display(Image(filename=str(OUT / "figures" / (n+".png"))))')
md('## 7. How do markets transition?\nThe transition matrix estimates latent state persistence. Argmax label runs have a different interpretation. First and last durations are censored. Confidence is an inferred state probability, not a crash probability.')
code('display(pd.read_csv(OUT / "results/transition_matrix.csv"))\nfor n in ["04_transition", "05_probabilities", "11_durations"]:\n    display(Image(filename=str(OUT / "figures" / (n+".png"))))')
md('## 8. Does it generalize, and can it help manage risk?\nThese portfolio series use held-out observations. Compare against both equity and fixed 60/40. Lower drawdown alone does not demonstrate successful timing: reducing average equity exposure can mechanically reduce risk. Inspect return and Sharpe too. Risk-free rate and cash yield are set to zero.')
code('display(metrics)\nfor n in ["07_drawdown", "08_equity", "09_sharpe", "10_volatility", "12_returns_by_state"]:\n    display(Image(filename=str(OUT / "figures" / (n+".png"))))\ndisplay(pd.read_csv(OUT / "results/performance_by_state.csv"))')
md('## 9. Robustness\nStructural sensitivity is evaluated on validation; test cost/allocation variants are exploratory. Do not select the best test variant and call it independent evidence. Likelihoods across different feature dimensions/scales are not directly comparable.')
code('display(pd.read_csv(OUT / "results/window_training_sensitivity.csv"))\ndisplay(pd.read_csv(OUT / "results/cost_allocation_sensitivity.csv"))')
md('## 10. Leakage & Backtest Integrity\nTrailing features; training-only transforms and state ranking; validation-only state-count choice; forward filtering; frozen test model; next-close execution; drift-aware two-leg costs and initial purchases. Training plots are retrospective, since the training fit saw that entire period. Historical adjusted data and fixed asset choices still introduce revision/selection limitations.')
md('## 11. What failed? Conclusions and future work\nIf using demo mode, the only defensible conclusion is that the implementation runs. In the verified synthetic run, the regime strategy reduced drawdown relative to benchmarks but had a worse Sharpe ratio; that is not proof of financial value. For historical runs, document poor metrics and unstable parameter results explicitly. No statistical significance is claimed. Future work: walk-forward refits, block-bootstrap intervals, multiple HMM starts and point-in-time data.')
code('print((OUT / "results/REPORT.md").read_text())\nprint("Outputs saved to", OUT)')
nb={'nbformat':4,'nbformat_minor':5,'metadata':{'kernelspec':{'display_name':'Python 3','language':'python','name':'python3'},'language_info':{'name':'python','version':'3.12'}},'cells':cells}
for i,c in enumerate(cells): c['id']=f'metis-{i:03d}'
(root/'notebooks/metis_kaggle.ipynb').write_text(json.dumps(nb,indent=1))
